# This is a basic workflow to help you get started with Actions

name: Netlify Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  # repository_dispatch:

# env:
  # GOOGLE_SERVICE_ACCOUNT_KEYS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEYS }}
  # SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: 'Checkout Source Code'

      # Setup Node Environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x

      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          yarn install --production
          yarn build
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './public'
          production-branch: main
          deploy-message: '${{ github.event.head_commit.message }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
